CREATE TABLE IF NOT EXISTS `trade_event_outbox` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `event_id` varchar(64) NOT NULL COMMENT '事件ID',
  `event_type` varchar(64) NOT NULL COMMENT '事件类型',
  `aggregate_type` varchar(64) NOT NULL COMMENT '聚合类型',
  `aggregate_id` varchar(64) NOT NULL COMMENT '聚合ID',
  `biz_id` varchar(128) NOT NULL COMMENT '业务幂等ID',
  `event_version` int NOT NULL DEFAULT '1' COMMENT '事件版本',
  `payload_json` text NOT NULL COMMENT '事件业务载荷',
  `topic` varchar(128) NOT NULL COMMENT 'Kafka topic',
  `status` tinyint NOT NULL DEFAULT '0' COMMENT '投递状态：0初始化、1已发送、2重试、3失败',
  `retry_count` int NOT NULL DEFAULT '0' COMMENT '投递重试次数',
  `next_retry_time` datetime DEFAULT NULL COMMENT '下次重试时间',
  `last_error` varchar(512) DEFAULT NULL COMMENT '最近一次失败原因',
  `occurred_at` datetime NOT NULL COMMENT '业务事实发生时间',
  `sent_time` datetime DEFAULT NULL COMMENT '发送成功时间',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_event_id` (`event_id`),
  UNIQUE KEY `uq_event_biz` (`event_type`, `biz_id`),
  KEY `idx_status_next_retry` (`status`, `next_retry_time`),
  KEY `idx_aggregate` (`aggregate_type`, `aggregate_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='交易事件 outbox';
